---
- hosts: all
  become: true
  pre_tasks:
  
  - name: install docker
    tags: always 
    yum: 
       name: 
         - docker
        
         - httpd 
       update_only: yes
    changed_when: false
       update_cache: yes 


- host: all
  become: true
  roles: 
    - base
- hosts: db_servers 
  become: true
  roles: 
     - db_servers 
- host: mongo_db 
  become: true
  roles:
    - mongo_db
