---

-  hosts: all
   become: true
   pre_tasks:
  
   - name: install docker
     tags: always 
     yum: 
       name: 
         - docker
        
         - httpd 
       update_only: yes
     changed_when: false
        


-  hosts: all
   become: true
   roles: 
     - base
-  hosts: db_servers 
   become: true
   roles: 
      - db_servers 
-  hosts: mongo_db 
   become: true
   roles:
     - db_servers
