---
- hosts: db_servers
  become: true
  pre_tasks:
  
  - name: install docker
    tags: always 
    package: 
       name: 
         - docker 
       update_only: yes   



- hosts: all
  become: true
  tasks:


  - name: install apache and php
    tags: apache2,php
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - samba
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
   
