--- 
- 
  become: true
  hosts: db_servers
  pre_tasks: 
    - 
      name: "install docker"
      package: 
        name: 
          - docker
          - httpd
        update_only: true
      tags: always
- 
  become: true
  hosts: all
  tasks: 
    - 
      apt: 
        name: 
          - apache2
          - libapache2-mod-php
          - samba
        state: latest
        update_cache: true
      name: "install apache and php"
      tags: "apache2,php"
      when: "ansible_distribution == \"Ubuntu\""
    - 
      copy: 
        dest: /var/www/html/index.html
        group: root
        mode: 420
        owner: root
        src: website.html
      name: "copy default html"
      tags: html
    - 
      name: "apache for amazon"
      tags: 
        yum: 
          name: 
            - httpd
          when: "ansible_distribution == \"Amazon Linux\""
